// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Snowflake.Bot.Data;

#nullable disable

namespace Snowflake.Bot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260805051046_AddGeminiMentions")]
    partial class AddGeminiMentions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Snowflake.Bot.Data.Entities.ColorRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "RoleId")
                        .IsUnique();

                    b.ToTable("ColorRoles");
                });

            modelBuilder.Entity("Snowflake.Bot.Data.Entities.CountingConfig", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CurrentRecord")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CurrentValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmojiCorrect")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmojiIncorrect")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmojiRecord")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtraChancesPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraChancesUsedToday")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Goal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastExtraChanceResetDate")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("LastUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoseMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordAtChainStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RecordCelebratedThisChain")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("CountingConfigs");
                });

            modelBuilder.Entity("Snowflake.Bot.Data.Entities.CountingStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BestContribution")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IncorrectCounts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCounts")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("CountingStats");
                });

            modelBuilder.Entity("Snowflake.Bot.Data.Entities.GuildConfig", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GeminiMentionsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("HubChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ModLogChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Volume")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("WelcomeChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WelcomeMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("Snowflake.Bot.Data.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModeratorTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TargetUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "TargetUserId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("Snowflake.Bot.Data.Entities.TempChannel", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.HasIndex("GuildId");

                    b.ToTable("TempChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
